project:
  type: website
  output-dir: _site

website:
  title: "WDI Assignment"
  navbar:
    left:
      - text: Slides
        href: slides.html
      - text: Report
        href: quarto.html

format:
  html:
    theme: cosmo